### ISSUE TITLE
sound doesn't work, Ventura😔

### ISSUE THREAD

**Issue by devely626** [AuthenTiiq/authentiiq-ryzen-hackintosh#15]
The list of audio devices is empty, there is no sound in the system, perhaps the revision of the motherboard is different? I will try to sort out alcids from those compatible with ALC887

**Comment by AuthenTiiq** [comment]
On my Gigabyte B450m ds3h it ALC887

Personally, I use my headphones via USB, so the ALC isn't much use to me.

What is your motherboard reference number?

**Comment by devely626** [comment]
J'ai exactement la même carte mère (Gigabyte B450M DS3H), exactement le même codec audio ALC887
cependant pour moi ce n'est pas un problème, tout le reste fonctionne, le son peut être restitué, merci pour l'EFI

**Comment by Sir-Linux** [comment]
I just updated to Ventura from Monterey. Sound was working previously. Motherboard is a Gigabyte H470M DS3H so has the Realtek ALC887.  Since updating it is like the 887 has disappeared.  I know it is working since I have another drive loaded with Monterey where when booted the sound works. Using the latest AppleALC and Lilu.
